###########################Agile 信息###########################
AGILE.URL=http://10.170.9.3:7001/Agile
AGILE.USER=admin
AGILE.PASSWORD=tartan
#TODO user password ashost
###########################SAP 连接信息###########################
SAP.CLIENT=800
SAP.USER=YD_RFC03
SAP.PASSWORD=yadeaauto
SAP.LANG=ZH
SAP.ASHOST=10.149.10.134
SAP.SYSNR=01

#TODO 接口发送参数
###########################零部件主数据 创建/修改 接口###########################
##接口函数
SAP.ITEM=ZFM_TR_MATERIAL
##接口发送参数
SAP.REQ=IT_DATA
##接口返回参数

###########################BOM主数据    创建   接口###########################
##接口函数
SAP.BOM.CREATE=ZFM_CREATE_BOM_NEW
##接口发送参数
SAP.BOM.CREATE-REQ=IT_DATA
##接口返回参数



###########################BOM主数据   修改   接口###########################
##接口函数
SAP.BOM.UPDATE=ZFM_UPDATE_BOM_NEW
##接口发送参数
SAP.BOM.REQ=IT_DATA
##接口返回参数

#########################   MDM 主数据创建接口 ############################
MDM.URL=https://mdm.yadea.com.cn/yadeaMdm/mdm/yadeaMat/matDataBulkOperation
LOG.URL=D:/plm/log4j2.xml
